spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minder
    username: root
    password: Arsenal93
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  application:
    jwt:
      secret: javainuse
