name: Java CI

on:
  push:
    branches: [master]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compile code
        run: mvn compile

  test:
    runs-on: ubuntu-latest
    name: test
    needs: compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run unit tests
        run: mvn test

  build:
    runs-on: ubuntu-latest
    name: build
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true

      - uses: actions/upload-artifact@v1
        with:
          name: jarfile
          path: target/

  docker-build:
    runs-on: ubuntu-latest
    name: Run docker build
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: jarfile
          path: target/
      - uses: gonuit/heroku-docker-deploy@v1.3.2 # GitHub action name (leave it as it is).
        with:
          email: wilssondaniel@gmail.com
          heroku_api_key: 57eb2e9c-d240-435a-a16c-b379270284d1
          heroku_app_name: hardwar
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          process_type: web
